# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-27 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
