# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-27 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_auto_20161128_0054'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='author',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='quote',
            managers=[
            ],
        ),
    ]
